### ISSUE TITLE
Appears to be broken

### ISSUE THREAD

**Issue by duncangroenewald** [JohannesHeinrich/garmin-connect-export#4]
This appears to be broken - gives an error "did not get a ticket in the response"

**Comment by AngelaKru** [comment]
So what worked for me:

Change the login URL from 'login' to 'signin':
private static string BASE_URL = "https://sso.garmin.com/sso/signin";

Then add an 'origin' header to the request:
            request.Headers.Add("origin", "https://sso.garmin.com");

Mine is once again working after these changes, I was getting the same invalid ticket error prior

**Comment by johannesh83** [comment]
Thank you @AngelaKru. Seems like Garmin did unfortunately again some changes. Will you create a pull request as you already applied the solution.
